# Generated by Django 5.1.6 on 2025-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0003_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
