# Generated by Django 5.1.6 on 2025-03-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0004_alter_blacklistedaccesstoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedAccessToken',
        ),
    ]
